image:
  file: .gitpod.Dockerfile
tasks:
  - init: |
      make
    command: |
      make tests
vscode:
  extensions:
    - ms-vscode.cpptools
    - notskm.clang-tidy
    - llvm-vs-code-extensions.vscode-clangd
